// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjektZespolowyGr3.Models;

#nullable disable

namespace ProjektZespolowyGr3.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20260422150001_AddListingTypeBack")]
    partial class AddListingTypeBack
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
