// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ProjektZespolowyGr3.Models;

#nullable disable

namespace ProjektZespolowyGr3.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20260422160001_AddCustomItemsToTradeProposalItem")]
    partial class AddCustomItemsToTradeProposalItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
